<h1>Application Program Interface</h1>

<p>An API connect your program to other software components.
You can communicate by given input and receiving output. <p>

<h2> REST APIs</h2>
<p>REST (Representational State Transfer) APIs allows communication between client and server over HTTP.</p>
<p>HTTP is a protocol for transferring data over the internet. Client sends requests to the server, and the server responds with the requested data via HTTP, usually containing a JSON file. After processing, the server returns the response to the client, usually also using a JSON file.</p>

<h2>PyCoinGecko for CoinGecko API</h2>
<p>PyCoinGecko is a Python wrapper for the CoinGecko API, which provides access to cryptocurrency data.</p>

In [ ]:
# install API package
!pip3 install pycoingecko

Defaulting to user installation because normal site-packages is not writeable
Collecting pycoingecko
  Downloading pycoingecko-3.2.0-py3-none-any.whl (10 kB)
Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 2.5 MB/s eta 0:00:01
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.9-cp39-cp39-macosx_10_9_universal2.whl (306 kB)
     |████████████████████████████████| 306 kB 7.8 MB/s eta 0:00:01
Collecting idna<4,>=2.5
  Downloading idna-3.18-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 30.3 MB/s eta 0:00:01
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 58.2 MB/s eta 0:00:01
Collecting certifi>=2017.4.17
  Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 67.2 MB/s eta 0:00:01
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, pycoingecko
Successfully installed certifi-2026.7.22 charset-normalizer-3.4.9 idna-3.18 pycoingecko-3.2.0 requests-2.32.5 urllib3-2.6.3
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [ ]:
from pycoingecko import CoinGeckoAPI
# API object
cg = CoinGeckoAPI()

# Using API to retrieve data
bitcoin_data = cg.get_coin_market_chart_by_id(id = 'bitcoin', vs_currency = 'usd', days = 30)
bitcoin_data['prices']

[[1782111609052, 63940.26315995606],
 [1782115204601, 64134.651134027],
 [1782118847268, 64087.37042490323],
 [1782122472085, 64055.179036193535],
 [1782126051388, 64068.498384986066],
 [1782129654969, 64594.71350884732],
 [1782133241538, 65095.257315744195],
 [1782136840441, 65468.626564180355],
 [1782140431274, 64888.927469478935],
 [1782144071989, 64754.92452119641],
 [1782147627748, 64683.704578473276],
 [1782151226444, 64556.49952209388],
 [1782154826012, 64301.39877649407],
 [1782158409489, 64417.748318432954],
 [1782162052591, 64365.9175955822],
 [1782165620586, 64235.021031055294],
 [1782169243113, 63911.612718239056],
 [1782172848091, 63957.19561383976],
 [1782176437436, 64045.666767229544],
 [1782180054183, 64079.82103359411],
 [1782183606902, 64144.39979492271],
 [1782187266162, 63980.98741876507],
 [1782190810677, 63621.26042010823],
 [1782194419877, 63313.7269410536],
 [1782198072714, 62866.90848700344],
 [1782201634076, 62850.76814022467],
 [1782205223936, 62311.40037519842],
 [1782208820133, 62307.34214427159],
 [1782212422496, 62264.18908247069],
 [1782216002705, 62451.49737098857],
 [1782219666432, 62199.8784487437],
 [1782223208342, 62383.94741826511],
 [1782226812347, 62457.865612986134],
 [1782230410077, 62378.52994283749],
 [1782234019382, 62492.81701127148],
 [1782237601758, 62300.737372444346],
 [1782241273228, 62171.87002961892],
 [1782244846790, 62310.62864515332],
 [1782248472728, 62385.33941347201],
 [1782252002489, 62530.759849035516],
 [1782255618680, 62515.95646051559],
 [1782259202283, 62651.93474257838],
 [1782262825089, 62912.97023760417],
 [1782266454309, 62883.37584853357],
 [1782270056003, 62583.0454660447],
 [1782273629180, 62676.59157469255],
 [1782277242294, 62703.951669706556],
 [1782280867103, 62802.23166347988],
 [1782284446435, 62699.01945275507],
 [1782288069698, 62568.95078726398],
 [1782291620413, 62716.04032481007],
 [1782295220726, 62621.29389792389],
 [1782298866483, 62379.401309585366],
 [1782302427973, 62815.96886427302],
 [1782306002033, 62538.57860514398],
 [1782309649062, 61236.55534272521],
 [1782313258433, 60985.864493824105],
 [1782316806775, 60204.220327509334],
 [1782320466298, 59783.05042276664],
 [1782324021576, 59297.73643929386],
 [1782327654081, 59507.187984197044],
 [1782331234821, 59822.24825588187],
 [1782334877862, 60882.548735749966],
 [1782338438249, 61005.378953134474],
 [1782342049952, 60783.200878396405],
 [1782345642693, 60990.53863518005],
 [1782349251018, 60664.90692436006],
 [1782352845624, 60812.426404174934],
 [1782356401287, 60629.714711165805],
 [1782360072163, 60788.38575979891],
 [1782363646865, 61257.61278932525],
 [1782367221948, 61534.43462777755],
 [1782370842041, 61646.00687766538],
 [1782374414641, 61816.442509036395],
 [1782378069213, 61606.905269718525],
 [1782381617388, 61652.90431812403],
 [1782385209157, 61211.78155908992],
 [1782388816892, 61185.54992485836],
 [1782392429614, 61114.65746062846],
 [1782396036454, 58188.668886715604],
 [1782399614612, 59419.45155775679],
 [1782403219924, 59513.72747967234],
 [1782406846587, 59234.5777533372],
 [1782410417544, 59534.099860815295],
 [1782414041470, 59430.91825964714],
 [1782417640952, 59237.365253537],
 [1782421241586, 59312.805434743896],
 [1782424820998, 60111.69113616151],
 [1782428436150, 59787.08233594131],
 [1782432003634, 59712.618061582114],
 [1782435652622, 59589.363566722495],
 [1782439249124, 59299.072111513124],
 [1782442825937, 58482.96476980456],
 [1782446427529, 59836.297717503796],
 [1782450026096, 59813.84530916572],
 [1782453635195, 59869.425120800624],
 [1782457260088, 60237.0568540939],
 [1782460810245, 60481.35722924747],
 [1782464512514, 60152.35271713132],
 [1782468023881, 59633.32449414534],
 [1782471616662, 59215.19340895525],
 [1782475207851, 59316.01978220941],
 [1782478897941, 59181.15371571542],
 [1782482489468, 60047.79171625427],
 [1782486096884, 59544.55798790487],
 [1782489615459, 60234.41217478131],
 [1782493281835, 59989.84009196498],
 [1782496871559, 59956.8650670713],
 [1782500471744, 59548.21995225559],
 [1782504152352, 59783.392831819365],
 [1782507629675, 59649.930123311075],
 [1782511303354, 59858.072565853494],
 [1782514888199, 59981.17710194979],
 [1782518502796, 60019.95786697783],
 [1782522107653, 59964.45026386145],
 [1782525659075, 59876.12754548514],
 [1782529330432, 60223.82465168318],
 [1782532814929, 60209.80787261281],
 [1782536500278, 60147.077420030015],
 [1782540090714, 60171.478533144495],
 [1782543635144, 60274.13576881021],
 [1782547226864, 60455.26973124937],
 [1782550839646, 60375.79046546325],
 [1782554403478, 60335.19971344227],
 [1782558027798, 60318.79468914347],
 [1782561762169, 60272.896834644176],
 [1782565328228, 60318.795624051476],
 [1782568959476, 60473.74809860174],
 [1782572431255, 60514.09495299602],
 [1782576158002, 60726.0944020887],
 [1782579650153, 60700.46947559311],
 [1782583242883, 60481.77726989441],
 [1782586865709, 60456.37514817717],
 [1782590447981, 60076.97687579784],
 [1782594047339, 60183.761872484516],
 [1782597632855, 60109.83787971532],
 [1782601337242, 60142.21183335991],
 [1782604895720, 59943.11077412465],
 [1782608478284, 60094.323390000915],
 [1782612010104, 60127.42543751148],
 [1782615675763, 60089.01267259338],
 [1782619335109, 60118.541800496205],
 [1782622836735, 60038.87607343662],
 [1782626436970, 59891.782608466485],
 [1782630056745, 59920.66782573778],
 [1782633653079, 60116.601882979696],
 [1782637335158, 60298.350227957766],
 [1782640930927, 60185.59725852188],
 [1782644414312, 60082.00970436492],
 [1782648004796, 60250.09690682865],
 [1782651677221, 60209.826283247254],
 [1782655219571, 59993.62219134955],
 [1782658845787, 59958.878845995176],
 [1782662488847, 59795.77601296277],
 [1782666133276, 59603.99470359071],
 [1782669704545, 59513.50156723828],
 [1782673220584, 59524.93799420059],
 [1782676897862, 59396.89382257217],
 [1782680533381, 59569.664031856664],
 [1782684057687, 59314.897022466685],
 [1782687678108, 58971.23519682808],
 [1782691331479, 59516.449485815276],
 [1782694939267, 59536.763045853324],
 [1782698460846, 59380.65908962489],
 [1782702055614, 59661.55398160819],
 [1782705650551, 59923.93226579998],
 [1782709275597, 59726.33088120169],
 [1782712949885, 59971.313088808965],
 [1782716440033, 59998.27530548425],
 [1782720081033, 59962.77802195896],
 [1782723687481, 59766.57617949523],
 [1782727324028, 59964.32556389398],
 [1782730940072, 60001.17115663765],
 [1782734411621, 59848.310873191185],
 [1782738023437, 59879.185745244955],
 [1782741709189, 59403.21046749944],
 [1782745231255, 59322.403378063944],
 [1782748877738, 59737.18874677538],
 [1782752491297, 59799.44547358118],
 [1782756086190, 60352.933054072964],
 [1782759697075, 60185.86090922262],
 [1782763294737, 60365.99092778629],
 [1782766951103, 60208.60225938614],
 [1782770549797, 60402.6398148205],
 [1782774086133, 60277.64965863437],
 [1782777614079, 60143.56968976742],
 [1782781247040, 59763.76807236464],
 [1782784800744, 59855.17763398167],
 [1782788413052, 59877.69088980854],
 [1782792101569, 59538.373932222115],
 [1782795702100, 59400.63642258716],
 [1782799288072, 59545.28581974851],
 [1782802886557, 59488.13160733083],
 [1782806491336, 59434.561635618695],
 [1782810046306, 59224.09548556559],
 [1782813750380, 59278.70670720093],
 [1782817243342, 59290.66415548365],
 [1782820909703, 59080.666508993316],
 [1782824500995, 58361.62212387054],
 [1782828143880, 58603.030121524156],
 [1782831678142, 58424.39729457026],
 [1782835266251, 58331.3311178704],
 [1782838812817, 58375.41692485716],
 [1782842509311, 58331.83443777217],
 [1782846054516, 58579.528664432866],
 [1782849686347, 58711.424716016336],
 [1782853295125, 58668.24249598245],
 [1782856829859, 58553.23708090124],
 [1782860476739, 58519.109561345475],
 [1782864033287, 58557.699161739816],
 [1782867624318, 58474.56780052823],
 [1782871214617, 58695.88415560775],
 [1782874839764, 59007.480156095095],
 [1782878442938, 59087.88649635893],
 [1782882035320, 59240.81479183014],
 [1782885709733, 59056.07800512759],
 [1782889251450, 58660.38219233212],
 [1782892903156, 58678.894153851295],
 [1782896458172, 58884.753538105266],
 [1782900051338, 58866.763614235475],
 [1782903719268, 58590.05322656013],
 [1782907276464, 58541.60278645741],
 [1782910893140, 58448.22896692919],
 [1782914440598, 59312.92896437234],
 [1782918018374, 59466.02292764383],
 [1782921648879, 60090.85821617794],
 [1782925345578, 59852.979014868964],
 [1782928869938, 60132.64834348138],
 [1782932489028, 60095.709313453386],
 [1782936101931, 59960.31569926729],
 [1782939610801, 60065.380452334844],
 [1782943210059, 60745.743247635626],
 [1782946845056, 60415.2229242068],
 [1782950521424, 59979.90070833996],
 [1782954081718, 59660.4839927567],
 [1782957656968, 60084.32991287333],
 [1782961291900, 60384.86661547189],
 [1782964891191, 60957.393957087705],
 [1782968444720, 60729.02277627768],
 [1782972087096, 60446.65072196339],
 [1782975695303, 60221.16622835474],
 [1782979251103, 60055.335102163546],
 [1782982900963, 60431.30338105714],
 [1782986480746, 61139.924936473275],
 [1782990093036, 61192.444687262076],
 [1782993671698, 61220.64052012101],
 [1782997204289, 61467.82857696401],
 [1783000880363, 61839.24095285028],
 [1783004413343, 61559.14539111479],
 [1783008044096, 61552.24644930286],
 [1783011707118, 61590.77616291104],
 [1783015222205, 61610.62755154093],
 [1783018898841, 61686.23259803437],
 [1783022498568, 61427.45640568673],
 [1783026082045, 61508.07375090117],
 [1783029663576, 61503.81872816729],
 [1783033278121, 61438.58446448573],
 [1783036882440, 61487.29901031284],
 [1783040514919, 61237.16135251831],
 [1783044118419, 61533.75646897373],
 [1783047690354, 61363.8521565249],
 [1783051313263, 61353.15167836988],
 [1783054903018, 61391.16847497167],
 [1783058468426, 61632.764774500036],
 [1783062103328, 61662.83761214957],
 [1783065705707, 61696.22955231316],
 [1783069268442, 61514.027723446874],
 [1783072944488, 61652.43657254511],
 [1783076405917, 61864.89102935673],
 [1783080029768, 61953.556085459175],
 [1783083604356, 61907.5900261029],
 [1783087208820, 62047.91006319728],
 [1783090936921, 62122.81633107454],
 [1783094423169, 61868.114447527485],
 [1783098101347, 62047.01380537126],
 [1783101675997, 62128.092588572435],
 [1783105309261, 62162.777580189475],
 [1783108906864, 62157.92997951671],
 [1783112551773, 62686.692450261944],
 [1783116093665, 62690.4786542379],
 [1783119747891, 62533.8264247283],
 [1783123265787, 62553.59200884509],
 [1783126914319, 62700.90133125955],
 [1783130521362, 62436.791019800745],
 [1783134085047, 62482.58461473608],
 [1783137688765, 62587.62471405669],
 [1783141329586, 62603.43275198819],
 [1783144817786, 62407.120168589456],
 [1783148475369, 62451.84682956266],
 [1783152088864, 62532.23831629742],
 [1783155675918, 62520.84723413682],
 [1783159354365, 62450.20119712215],
 [1783162956179, 62482.39506667081],
 [1783166495991, 62453.12714663282],
 [1783170040893, 62610.396860971974],
 [1783173684725, 62536.59571423263],
 [1783177209430, 62633.96023435144],
 [1783180883968, 62880.762249371735],
 [1783184495565, 62876.142857469764],
 [1783188111011, 63265.08190642989],
 [1783191689251, 63117.40706240529],
 [1783195356251, 63258.54754066335],
 [1783198890842, 63196.956647480525],
 [1783202423403, 63266.54853473329],
 [1783206027292, 63133.65522954236],
 [1783209701864, 63094.24017750663],
 [1783213332290, 62911.17832947541],
 [1783216906866, 62843.35957438356],
 [1783220416303, 62631.116007543984],
 [1783224153905, 62734.25655011185],
 [1783227751688, 62785.11026004227],
 [1783231261886, 62709.51187800394],
 [1783234855938, 62724.35082043866],
 [1783238482956, 62978.095888553216],
 [1783242085515, 62887.67049149987],
 [1783245628703, 62566.15760554671],
 [1783249263556, 62694.52324430207],
 [1783252895865, 62615.486952953535],
 [1783256451714, 62677.224459595],
 [1783260044293, 62737.554656126806],
 [1783263699161, 62739.572214585096],
 [1783267288802, 62687.39820897023],
 [1783270886169, 62592.79284419807],
 [1783274467345, 62575.48273011255],
 [1783278033771, 62762.70842480428],
 [1783281652420, 62724.48656942632],
 [1783285246671, 62687.03341572992],
 [1783288843039, 63091.255621016324],
 [1783292440928, 63625.70218985658],
 [1783296079394, 63546.43013166118],
 [1783299650005, 63664.44947588352],
 [1783303269761, 63517.88397289706],
 [1783306800199, 63356.81634247567],
 [1783310544896, 63214.39765600102],
 [1783314085254, 63212.03855536063],
 [1783317746663, 63062.9316093853],
 [1783321233492, 62933.16116759757],
 [1783324834891, 63035.84457747941],
 [1783328442551, 62835.1273290497],
 [1783332095297, 62602.19666873886],
 [1783335620742, 62753.1882449598],
 [1783339290630, 62629.58604555236],
 [1783342846157, 61715.901782077715],
 [1783346501059, 61780.449238816414],
 [1783350061330, 61968.36690072932],
 [1783353637197, 63436.93887280679],
 [1783357290357, 63655.61229080628],
 [1783360859579, 63542.08000663692],
 [1783364443453, 63674.372381924],
 [1783368013701, 63711.967437081395],
 [1783371666629, 63795.073329467814],
 [1783375359811, 64371.47818824933],
 [1783378877744, 64180.63420514519],
 [1783382454890, 63994.68116388147],
 [1783386018620, 64158.33162160982],
 [1783389698807, 63854.42907009023],
 [1783393239860, 63275.803446682585],
 [1783396951031, 63124.7255654564],
 [1783400489854, 63055.22636161977],
 [1783404006604, 63093.52474767431],
 [1783407679851, 63295.03276766405],
 [1783411293293, 63043.643597929586],
 [1783414875726, 63067.49655854592],
 [1783418468863, 63191.92703981319],
 [1783422098077, 63202.42235299024],
 [1783425638215, 63338.135433245836],
 [1783429217362, 63407.301844394664],
 [1783432871625, 63000.05499932012],
 [1783436519957, 63507.95601078837],
 [1783440041772, 63865.49136103849],
 [1783443649124, 63942.09671686718],
 [1783447200992, 64134.38775357911],
 [1783450823000, 63658.43220461216],
 [1783454491026, 63766.30289430432],
 [1783458005060, 63641.221279416444],
 [1783461626490, 63372.597940312146],
 [1783465249661, 63505.74328204638],
 [1783468913423, 63287.204623191705],
 [1783472428019, 63573.84506209216],
 [1783476099654, 63001.391652521525],
 [1783479611431, 62932.52174162355],
 [1783483257809, 62716.95149636293],
 [1783486806413, 62735.112422890656],
 [1783490466917, 62583.96837804984],
 [1783494060089, 62600.141430180454],
 [1783497627172, 62825.39569794576],
 [1783501348501, 61984.20323442917],
 [1783504948530, 62014.74797212771],
 [1783508452005, 62091.43336056865],
 [1783512090052, 62246.096425569114],
 [1783515657460, 61932.05086676209],
 [1783519318858, 61831.22745667842],
 [1783522902346, 61842.84560816078],
 [1783526459835, 61641.213975719205],
 [1783530079614, 62054.78429083154],
 [1783533675416, 62048.00605643022],
 [1783537272744, 62123.72638065353],
 [1783540885679, 62195.710556983504],
 [1783544477410, 62056.45927908783],
 [1783548122550, 62144.73025971306],
 [1783551688396, 62267.37381989537],
 [1783555346396, 62252.63748967275],
 [1783558901482, 62057.24234087997],
 [1783562471528, 61855.58077868091],
 [1783566096552, 61740.75242165106],
 [1783569645144, 61931.83568226704],
 [1783573212991, 62388.799997011505],
 [1783576823621, 62513.2301450384],
 [1783580413412, 62820.149627589315],
 [1783584032122, 62947.80102698248],
 [1783587665072, 62836.64826003586],
 [1783591201674, 62892.293535390665],
 [1783594822345, 62712.089962465136],
 [1783598414063, 62726.73097400199],
 [1783602092232, 62570.820826883464],
 [1783605691900, 62968.05424026797],
 [1783609214776, 62947.935198366315],
 [1783612882763, 62819.43817638452],
 [1783616450444, 62652.276781562185],
 [1783620094358, 63076.73003282413],
 [1783623669589, 63158.21618374233],
 [1783627235662, 63202.575673133855],
 [1783630832919, 63255.281135642144],
 [1783634469590, 63233.95531837552],
 [1783638076035, 63178.828901258355],
 [1783641649864, 63201.08806990343],
 [1783645250002, 63045.18746663233],
 [1783648896379, 63681.16647688241],
 [1783652498228, 63919.6728866854],
 [1783656056169, 63881.11532044424],
 [1783659633411, 64004.05069425178],
 [1783663248135, 64060.62365144604],
 [1783666887187, 63807.168886962325],
 [1783670486275, 63950.301083552404],
 [1783674110328, 64212.07079433152],
 [1783677698087, 64344.57686298755],
 [1783681282990, 64369.17004777795],
 [1783684912137, 64360.08798509396],
 [1783688461690, 64246.64072845215],
 [1783692074248, 64442.51730042664],
 [1783695673133, 63879.560460151944],
 [1783699254477, 63961.53854038046],
 [1783702883375, 64119.29884229157],
 [1783706466299, 63799.59845515737],
 [1783710077611, 63756.88286384032],
 [1783713620072, 63880.81340092693],
 [1783717249699, 63800.85162223474],
 [1783720851798, 63955.87380446337],
 [1783724488525, 64065.46308731039],
 [1783728102271, 64118.700579107266],
 [1783731725329, 64090.985162830504],
 [1783735259925, 63983.96626764876],
 [1783738848727, 64115.522860571924],
 [1783742484797, 64115.37631038539],
 [1783746010577, 64086.92184183047],
 [1783749643735, 64125.93552085215],
 [1783753227618, 64167.142957502365],
 [1783756810782, 64110.967829055204],
 [1783760431965, 64209.99503621056],
 [1783764036448, 64104.14383795518],
 [1783767663235, 64117.181131837984],
 [1783771304085, 64142.03562105326],
 [1783774857886, 64135.07789561458],
 [1783778428971, 64188.71487099244],
 [1783782011610, 64311.1039631105],
 [1783785704467, 64110.189634873896],
 [1783789286586, 64128.165827774385],
 [1783792852668, 64263.63534810441],
 [1783796461855, 64279.15675534047],
 [1783800111064, 64241.07631095752],
 [1783803641252, 64339.095199074836],
 [1783807217018, 64303.19087890115],
 [1783810901810, 64154.8812983746],
 [1783814460088, 63785.019944129],
 [1783818079738, 63795.5534612457],
 [1783821626237, 64083.899429257246],
 [1783825308294, 64063.16077869598],
 [1783828904291, 64133.10697088716],
 [1783832412575, 63940.97636885769],
 [1783836078985, 63941.1451891897],
 [1783839706488, 63724.00477666906],
 [1783843307207, 63849.17710443917],
 [1783846842175, 63944.78172943581],
 [1783850512741, 63922.04380563007],
 [1783854071040, 63837.20446081583],
 [1783857628134, 63971.89666202366],
 [1783861261101, 63985.68399412193],
 [1783864825336, 63985.723272603704],
 [1783868438551, 64171.54979050959],
 [1783872073689, 64124.30325557406],
 [1783875606769, 64126.799872384305],
 [1783879219623, 64037.39022055867],
 [1783882811956, 64109.22648415865],
 [1783886491485, 64196.767261017034],
 [1783890006499, 64156.76696807561],
 [1783893688145, 63892.4023151634],
 [1783897267767, 63861.436067138355],
 [1783900856542, 63746.44102430586],
 [1783904443048, 64012.312805316506],
 [1783908037637, 63421.28198419309],
 [1783911714549, 63320.631830206046],
 [1783915228313, 62775.55569582625],
 [1783918817344, 62670.584741553386],
 [1783922458986, 62728.009514842604],
 [1783926081129, 62747.21283925193],
 [1783929661816, 62968.23419840407],
 [1783933259219, 63140.68261699306],
 [1783936913095, 63038.51906996177],
 [1783940488824, 62828.859662356306],
 [1783944059871, 62843.21259949802],
 [1783947630826, 62566.90043706515],
 [1783951241850, 62252.287442566994],
 [1783954889057, 62705.622758880134],
 [1783958503138, 62548.83381235003],
 [1783962103567, 62212.97915238394],
 [1783965680438, 61911.944604665034],
 [1783969268931, 61965.06394311452],
 [1783972893507, 62205.61148259532],
 [1783976454659, 62128.654119429666],
 [1783980013577, 62037.374928324374],
 [1783983637952, 61848.880649850274],
 [1783987248251, 62242.25280265039],
 [1783990897840, 62480.43131648802],
 [1783994464940, 62468.129310434924],
 [1783998040561, 62476.08840224786],
 [1784001640732, 62498.68003814867],
 [1784005245054, 62668.07073804778],
 [1784008879884, 62638.25366915974],
 [1784012445527, 62531.98817446177],
 [1784016044611, 62483.669806718775],
 [1784019681718, 62622.78772915974],
 [1784023256209, 62556.167750696244],
 [1784026913101, 62746.50658907209],
 [1784030487702, 62782.167004497256],
 [1784034079755, 63863.66447397565],
 [1784037703064, 63763.75834652051],
 [1784041238228, 64030.29581969912],

In [11]:
# Convert the data into a pandas DataFrame
import pandas as pd
df = pd.DataFrame(bitcoin_data['prices'], columns=['TimeStamp', 'Price'])
# Convert the timestamp from milliseconds to a datetime object
df['Date'] = pd.to_datetime(df['TimeStamp'], unit='ms')
df

         TimeStamp         Price                    Date
0    1782111609052  63940.263160 2026-06-22 07:00:09.052
1    1782115204601  64134.651134 2026-06-22 08:00:04.601
2    1782118847268  64087.370425 2026-06-22 09:00:47.268
3    1782122472085  64055.179036 2026-06-22 10:01:12.085
4    1782126051388  64068.498385 2026-06-22 11:00:51.388
..             ...           ...                     ...
716  1784689236306  66258.646099 2026-07-22 03:00:36.306
717  1784692899684  66154.702883 2026-07-22 04:01:39.684
718  1784696461280  66327.496860 2026-07-22 05:01:01.280
719  1784700061125  65934.304011 2026-07-22 06:01:01.125
720  1784703589000  65884.519668 2026-07-22 06:59:49.000

[721 rows x 3 columns]

In [15]:
# Create a candlestick plot
candlestick_data = df.groupby(df.Date.dt.date).agg({'Price':['min', 'max', 'first', 'last']})
candlestick_data

                   Price
                     min           max         first          last
Date
2026-06-22  63911.612718  65468.626564  63940.263160  63911.612718
2026-06-23  62171.870030  64144.399795  63957.195614  62515.956461
2026-06-24  59297.736439  62912.970238  62651.934743  60783.200878
2026-06-25  58188.668887  61816.442509  60990.538635  59787.082336
2026-06-26  58482.964770  60481.357229  59712.618062  59981.177102
2026-06-27  59876.127545  60726.094402  60019.957867  60142.211833
2026-06-28  58971.235197  60298.350228  59943.110774  58971.235197
2026-06-29  59322.403378  60402.639815  59516.449486  60277.649659
2026-06-30  58331.331118  60143.569690  60143.569690  58519.109561
2026-07-01  58448.228967  60745.743248  58557.699162  60415.222924
2026-07-02  59660.483993  61839.240953  59979.900708  61438.584464
2026-07-03  61237.161353  62690.478654  61487.299010  62533.826425
2026-07-04  62407.120169  63266.548535  62553.592009  63133.655230
2026-07-05  62566.157606  63625.702190  63094.240178  63625.702190
2026-07-06  61715.901782  64371.478188  63546.430132  64180.634205
2026-07-07  63000.054999  64158.331622  63994.681164  63505.743282
2026-07-08  61641.213976  63573.845062  63287.204623  62267.373820
2026-07-09  61740.752422  63255.281136  62252.637490  63178.828901
2026-07-10  63045.187467  64442.517300  63201.088070  64065.463087
2026-07-11  63983.966268  64339.095199  64118.700579  64154.881298
2026-07-12  63724.004777  64196.767261  63785.019944  63861.436067
2026-07-13  61848.880650  64012.312805  63746.441024  61848.880650
2026-07-14  62242.252803  64829.306133  62242.252803  64829.306133
2026-07-15  64458.853512  65385.066571  64964.475377  64831.339477
2026-07-16  63920.247714  64871.038481  64722.057923  63920.247714
2026-07-17  62779.349904  64202.844020  63788.929018  63933.544566
2026-07-18  63859.327784  64774.657258  63892.114184  64774.657258
2026-07-19  64345.970646  64793.264461  64793.264461  64637.030711
2026-07-20  63839.013907  65526.402664  64679.765086  65094.287536
2026-07-21  65190.539149  66825.625715  65199.437784  66257.336965
2026-07-22  65884.519668  66616.981147  66506.886728  65884.519668

In [23]:
!pip3 install plotly
!pip3 install nbformat

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in /Users/gohzhirong/Library/Python/3.9/lib/python/site-packages (6.9.0)
Requirement already satisfied: packaging in /Users/gohzhirong/Library/Python/3.9/lib/python/site-packages (from plotly) (26.2)
Requirement already satisfied: narwhals>=1.15.1 in /Users/gohzhirong/Library/Python/3.9/lib/python/site-packages (from plotly) (2.21.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
Collecting nbformat
  Downloading nbformat-5.10.4-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 399 kB/s eta 0:00:01
Collecting fastjsonschema>=2.15
  Downloading fastjsonschema-2.21.2-py3-none-any.whl (24 kB)
Collecting jsonschema>=2.6
  Downloading jsonschema-4.25.1-py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 2.5 MB/s eta 0:00:01
Requirement already satisfied: traitlets>=5.1 in /Users/gohzhirong/Library/Python/3.9/lib/python/site-packages (from nbformat) (5.15.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/gohzhirong/Library/Python/3.9/lib/python/site-packages (from nbformat) (5.8.1)
Collecting jsonschema-specifications>=2023.03.6
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Collecting referencing>=0.28.4
  Downloading referencing-0.36.2-py3-none-any.whl (26 kB)
Collecting rpds-py>=0.7.1
  Downloading rpds_py-0.27.1-cp39-cp39-macosx_11_0_arm64.whl (354 kB)
     |████████████████████████████████| 354 kB 4.0 MB/s eta 0:00:01
Collecting attrs>=22.2.0
  Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 9.0 MB/s  eta 0:00:01
Requirement already satisfied: platformdirs>=2.5 in /Users/gohzhirong/Library/Python/3.9/lib/python/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.4.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /Users/gohzhirong/Library/Python/3.9/lib/python/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.16.0)
Installing collected packages: rpds-py, attrs, referencing, jsonschema-specifications, jsonschema, fastjsonschema, nbformat
Successfully installed attrs-26.1.0 fastjsonschema-2.21.2 jsonschema-4.25.1 jsonschema-specifications-2025.9.1 nbformat-5.10.4 referencing-0.36.2 rpds-py-0.27.1
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [26]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Candlestick(x=candlestick_data.index,
                open=candlestick_data['Price']['first'],
                high=candlestick_data['Price']['max'],
                low=candlestick_data['Price']['min'],
                close=candlestick_data['Price']['last'])]
                )

fig.update_layout(
    xaxis_rangeslider_visible=False, 
    xaxis_title='Date', 
    yaxis_title='Price (USD $)',
    title='Bitcoin Price Candlestick Chart Over Past 30 Days'
)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'close': {'bdata': ('zUdjm/M070BMFVObfobuQOGHmG3mre' ... '4zycjvQMdwNWQVLfBA9gmPUMgV8EA='),
                        'dtype': 'f8'},
              'high': {'bdata': ('71LQDJT370DFuB7LDFLvQGi7LwwfuO' ... '/izP7vQIja7QKaUPBAq3bHso9D8EA='),
                       'dtype': 'f8'},
              'low': {'bdata': ('zUdjm/M070D6WkjXe1vuQFQj6ZA39O' ... '5x4CvvQDSrtEDR1O9A9gmPUMgV8EA='),
                      'dtype': 'f8'},
              'open': {'bdata': ('nW3Oa4g470CN9HdCpjrvQIpEael9l+' ... 'V7+JTvQFbqUwLu1e9AER0KMK488EA='),
                       'dtype': 'f8'},
              'type': 'candlestick',
              'x': array([datetime.date(2026, 6, 22), datetime.date(2026, 6, 23),
                          datetime.date(2026, 6, 24), datetime.date(2026, 6, 25),
                          datetime.date(2026, 6, 26), datetime.date(2026, 6, 27),
                          datetime.date(2026, 6, 28), datetime.date(2026, 6, 29),
                          datetime.date(2026, 6, 30), datetime.date(2026, 7, 1),
                          datetime.date(2026, 7, 2), datetime.date(2026, 7, 3),
                          datetime.date(2026, 7, 4), datetime.date(2026, 7, 5),
                          datetime.date(2026, 7, 6), datetime.date(2026, 7, 7),
                          datetime.date(2026, 7, 8), datetime.date(2026, 7, 9),
                          datetime.date(2026, 7, 10), datetime.date(2026, 7, 11),
                          datetime.date(2026, 7, 12), datetime.date(2026, 7, 13),
                          datetime.date(2026, 7, 14), datetime.date(2026, 7, 15),
                          datetime.date(2026, 7, 16), datetime.date(2026, 7, 17),
                          datetime.date(2026, 7, 18), datetime.date(2026, 7, 19),
                          datetime.date(2026, 7, 20), datetime.date(2026, 7, 21),
                          datetime.date(2026, 7, 22)], dtype=object)}],
    'layout': {'template': '...',
               'title': {'text': 'Bitcoin Price Candlestick Chart Over Past 30 Days'},
               'xaxis': {'rangeslider': {'visible': False}, 'title': {'text': 'Date'}},
               'yaxis': {'title': {'text': 'Price (USD $)'}}}
})